# Site settings
title: Cloud and DevOps
url: "ajeetchouksey.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Europe/London
description: ""

# Your information
#see _data\authors.yml
excerpt_separator: <!--more-->
google_analytics:  UA-101864870-1
google_verify: GKeGILLEWvsJwRfdYMqqoMDZKOBZPWIWpHP9K2uIXHI
production: true

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: azure365   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /:categories/:title
markdown: kramdown
gems:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-redirect-from

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
